# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Testing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MarqueeLabel' # For auto scroll label or marquee base on label
  pod 'PanModal' # For alert has scroll
  pod 'Localize-Swift' # For translate or localize (Langauge)
  pod 'SDWebImage' # For get image from api
end
